spring:
  application:
    namer: gateway-service
    cloud:
      config:
        import-check:
        enable: false
    
server: 
  port: 9090    
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
